---
title: "plot_ly and dashboard"
output: html_document
date: "2025-10-27"
---

Interactivity is great.

Here's the tidyverse.

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)

library(p8105.datasets)
```

Load airbnb dataset.

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(
    rating = review_scores_location / 2
  ) |> 
  select(
    neighbourhood_group, neighbourhood, rating,
    price, room_type, lat, long
  ) |> 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price <= 500,
    price >= 100
  )
```

Make a scatterplot but interactive this time.

```{r}
nyc_airbnb |> 
  mutate(
    label = str_c("Price: $", price, "\nRating: ", rating)
  ) |> 
  plot_ly(
    x = ~lat,y = ~long, color = ~price, 
    text = ~label,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```


Let's make boxplot:

```{r}
nyc_airbnb |> 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, price)
  ) |> 
  plot_ly(
    x = ~neighbourhood, y = ~price, color = ~neighbourhood,
    type = "box", colors = "viridis"
  )
```



Maybe barcharts next?

```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, n)
  ) |> 
  plot_ly(
    x = ~neighbourhood, y =c~n,
    type = "bar"
  )
```


